### ISSUE TITLE
Where to find source used for building cocoapods (.podspec)

### ISSUE THREAD

**Issue by SashaMilic** [Azure-Samples/azure-iot-samples-ios#12]
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

>
Can't find .podspec. Here is the link to .json:
https://github.com/CocoaPods/Specs/blob/master/Specs/3/8/4/AzureIoTHubClient/1.2.4/AzureIoTHubClient.podspec.json
But it is the compiled version
The original one is in ruby. Where we can find link to it?
>

### Expected/desired behavior
If it's open source project where is .podspec file?
>

### OS and Version?
iOS
Versions  13.3
>
We are trying to port lib for iOS to work on watchOS. .podspec will be helpfull.
Where to find source used for building cocoapods (.podspec) for using AureIoTHub for iOS?
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/ios/CocoaPods.md
> ---------------------------------------------------------------

**Comment by jbobotek** [comment]
Oh yes, I believe we talked about this a couple months ago now. Fairly sure I forwarded the podspec repo, but here it is in case you need to find it again: https://github.com/jbobotek/azure-iot-sdk-c-podspecs
